# Generated by Django 2.0.13 on 2020-11-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
    ]
