# Generated by Django 2.0.13 on 2020-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0005_auto_20201101_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='train',
            field=models.IntegerField(choices=[(1, 'VANDE BHARAT EXPRESS'), (2, 'SHATABDI EXPRESS'), (3, 'DURONTO EXPRESS'), (4, 'GATIMAAN EXPRESS'), (5, 'RAJDHANI EXPRESS')], default=1),
        ),
    ]
