# Generated by Django 2.0.13 on 2020-11-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0006_auto_20201101_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='tproj.Station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='tproj.Station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_train', to='tproj.Train'),
        ),
    ]
