# Generated by Django 2.0.13 on 2020-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0007_auto_20201103_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Other'), ('2', 'Male'), ('3', 'Female')], default=1),
        ),
    ]
