# Generated by Django 2.0.13 on 2020-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0008_auto_20201103_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'Male'), ('F', 'Female')], default='O', max_length=5),
        ),
    ]
