# Generated by Django 2.0.13 on 2020-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0009_auto_20201113_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='tickets_number',
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=1),
        ),
    ]
