# Generated by Django 2.0.13 on 2020-11-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tproj', '0010_auto_20201115_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='passengers',
            new_name='seat',
        ),
    ]
